# Generated by Django 5.0.3 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Instrumento',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='materia',
            new_name='instrumento',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='nombre',
            new_name='marca',
        ),
    ]
